spring.application.name=student-management

# ===== DATABASE =====
spring.datasource.url=jdbc:mysql://localhost:3306/studentmanagementsystem1
spring.datasource.username=root
spring.datasource.password=Letrunghieu2005

# ===== JPA =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===== GEMINI API =====
gemini.api.key=YOUR_API_KEY_HERE
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent

# ===== FILE UPLOAD =====
app.upload.dir=uploads